const QuestionsActionTypes = {
	LOAD_CATEGORIES: 'LOAD_CATEGORIES',
	NEW_CATEGORY: 'NEW_CATEGORY',
	SELECT_QUESTION: 'SELECT_QUESTION',
	REMOVE_QUESTION: 'REMOVE_QUESTION',
	CHALLENGE: 'CHALLENGE',
};
export default QuestionsActionTypes;
