const UsersActionTypes = {
	ADD_USER: 'ADD_USER',
	REMOVE_LIFE: 'REMOVE_LIFE',
	CLEAR_USER: 'CLEAR_USER',
	SELECT_CURRENT_USER: 'SELECT_CURRENT_USER',
	SELECT_CHALLENGER: 'SELECT_CHALLENGER',
	SELECT_NEW_USER: 'SELECT_NEW_USER',
};
export default UsersActionTypes;
